//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baker
{
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.Data.SqlClient;
    using System.Windows.Forms;

    public partial class ingridients
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ingridients()
        {
            this.ElementGoods = new HashSet<ElementGoods>();
        }
    
        public int Idingridient { get; set; }
        public string Name { get; set; }
        public double Quantity { get; set; }
        public int Unit { get; set; }
        public int IdProvider { get; set; }
        public int IdUnitMoney { get; set; }
        public decimal Price { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ElementGoods> ElementGoods { get; set; }
        public virtual Provider Provider { get; set; }
        public virtual UnitMoney UnitMoney { get; set; }
        public virtual Units Units { get; set; }
        public void Read(DataTable tableIng)
        {
            using (SqlConnection conn = new SqlConnection(@"Data Source=DESKTOP-FTH1RKF;Initial Catalog=Pekarnya2;Integrated Security=True"))
            {
                try
                {
                    conn.Open();
                    var query = "select ing.Idingridient, ing.Name, ing.Quantity, un.Name, pr.Name, ing.Price, unm.Name from ingridients as ing inner join Provider as pr on ing.IdProvider=pr.Idprovider inner join Units as un on ing.Unit = un.IdUnit inner join UnitMoney as unm on ing.IdUnitMoney = unm.IdUnit";
                    SqlCommand ReadCmd = new SqlCommand(query, conn);
                    SqlDataReader reader = ReadCmd.ExecuteReader();
                    tableIng.Load(reader);
                    reader.Close();
                }
                catch (Exception ex)
                {
                    MessageBox.Show(ex.ToString());
                }
                finally
                {
                    conn.Close();
                }

            }
        }
    }
}
